#!/bin/bash

clear

echo -n "Where are we?(p=production, AnythingElse=develop, default=d) " && read what

username=test
password=!_T123456789T_!
database=test_db
cport=3333

if [ "$what" = "p" ]; then

clear

echo -n "Enter a Username for database: " && read username
echo -n "Enter a Password for your username: " && read password
echo -n "Enter a your Database name: " && read database
echo -n "Enter your custom port(if you want, default=3333): " && read cport

if [ -z "$cport" ]; then; cport=3333; fi

clear

fi

echo run these commands manually down here: | lolcat -d 1 && echo
echo "CREATE USER '$username' IDENTIFIED WITH mysql_native_password BY '$password';"
echo "GRANT ALL PRIVILEGES ON *.* TO '$username';"
echo "FLUSH PRIVILEGES;"
echo "CREATE DATABASE $database DEFAULT CHARACTER SET utf8mb4  DEFAULT COLLATE utf8mb4_general_ci;"
echo "exit"
echo && echo and everything should be done | lolcat -d 1 && echo
sudo mysql -u root || sudo mysql -u root -p

if [ "$what" = "p" ]; then

echo -n "HOST=127.0.0.1
PORT=$cport
NODE_ENV=production
APP_URL=http://\${HOST}:\${PORT}
CACHE_VIEWS=false
APP_KEY=ZhtaQDlMrSKwLKDs2DpQ5YwMDAd6LXU7
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=$username
DB_PASSWORD=$password
DB_DATABASE=$database
SESSION_DRIVER=cookie
HASH_DRIVER=bcrypt" > .env

# Generating an APP_KEY for our project
echo Generationg a key for our APP_KEY field in .env config file | lolcat -d 1 && echo
adonis key:generate

else

echo -n "HOST=127.0.0.1
PORT=$cport
NODE_ENV=development
APP_URL=http://\${HOST}:\${PORT}
CACHE_VIEWS=false
APP_KEY=ZhtaQDlMrSKwLKDs2DpQ5YwMDAd6LXU7
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=$username
DB_PASSWORD=$password
DB_DATABASE=$database
SESSION_DRIVER=cookie
HASH_DRIVER=bcrypt" > .env

fi

echo && echo Everything should be good, fine and done | lolcat -d 1
echo Have fun | lolcat -d 1 && echo